### ISSUE TITLE
Improve wpt running scripts

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#394]
These are the steps I've identified as useful next steps to get more frequent runs. It would improve both the time taken to produce a run and the reliability of the running infrastructure in general. It would also allow us to add lots of cheap, small virtual machines alongside our current more expensive GPU-based machines and run non-GPU tasks on cheaper machines.

- [x] [Identify and build a central server which identifies the correct SHA to be run and controls the other machines](https://github.com/w3c/wptdashboard/issues/395)

- [x] ~~[Generate a copy of the repo at specified SHA and loop through directories therein (`for x in ``ls -1d *``; do foo; done`)](https://github.com/w3c/wptdashboard/issues/396)~~

- [x] ~~[The machine generates a shell script which takes the required files from the SHA and the modified run script and sends them to a machine in the pool. ](https://github.com/w3c/wptdashboard/issues/397)~~

- [ ] [At the end of the script, the machine POSTs the results, with the SHA and browser back to the control machine. The script also removes itself.](https://github.com/w3c/wptdashboard/issues/398)

- [ ] [When the machine receives a payload, it is verified (n% of tasks passed) and saved locally. Another payload is sent to machines in the pool.](https://github.com/w3c/wptdashboard/issues/399)

- [ ] [When the directories have all completed, the results are bundled up and sent to the wpdashboard.](https://github.com/w3c/wptdashboard/issues/400)

This would leave a single machine in charge of all uploads. It would allow us to shard by directory and across machines having lots of small machines that can run jobs (jobs that may require a GPU could be reserved only for GPU machines).

**Comment by jgraham** [comment]
I'm coming at this super-late, and I haven't followed this work closely enough. So take this as you will. 

The huge set of issues and requirements here looks really complex and I worry there's a long tail of complexity to make the system robust., It strikes me that many of these same reuirements are already solved by Mozilla's taskcluster system, which powers our internal CI and is also available to use from GitHub. Very roughly it provides the ability to spawn tasks running in custom docker images across a (large) number of worker machines. Internally we have Linux/Windows/OSX testing all running on TaskCluster, but afaik only Linux and (maybe) Windows are available to GitHub users at the moment. There may also be other limitations on what's avaiable through GitHub, but I'm pretty sure we could work with the TC team to address any limitations we face. The documentation for taskcluster is at [1].

As an example, I set up my wpt fork to run testharness tests in Firefox and Chrome, chunked into 12 just running one chunk in each. This will run on every commit to master. The runs are at [2] (I didn't figure out if there's built-in artifact uploading for GitHub yet, or whether one needs to provide ones own S3 account e.g.)

[1] https://docs.taskcluster.net/
[2] https://tools.taskcluster.net/groups/THc-FueaTwa4k57DvWsUQQ

**Comment by jgraham** [comment]
(fyi, those tasks are marked as "failed" because not all tests passed. Obviously that's not the right semantics for our case).

**Comment by mattl** [comment]
@jgraham thanks. I don't think this will actually be all that complicated, I'm just breaking it up into lots of small steps to make it easier to manage the work. But I'll take a look.

**Comment by mattl** [comment]
We've moved in a different direction on this, with chunking. Those changes are now in run.py.
